version: "3"

services:
  auth-database:
    image: mongo
    ports:
      - "27017:27017"

  status-database:
    build: Status-Database
    ports:
      - 5432:5432

  wallet-auth:
    build: Wallet-Auth
    depends_on: [auth-database, status-database]
    ports:
      - 8000:8000
  wallet-admin:
    build: Wallet-admin
    depends_on: [auth-database, status-database]
    ports:
      - 4500:4500

  wallet-sync:
    build: Wallet-Sync
    depends_on: [status-database]
    ports:
      - 7000:7000

  wallet-transaction:
    build: Wallet-Transaction
    depends_on: [status-database]
    ports:
      - 10000:10000
