version: "3"

services:
  auth-database:
    image: mongo
    ports:
      - "27017:27017"

  database:
    build: Database
    ports:
      - 5432:5432

  cache:
    image: redis
    ports:
      - 6379:6379

  wallet-block:
    build: Wallet-Block
    depends_on: [cache, auth-database, database]
    ports:
      - 9000:9000

  wallet-auth:
    build: Wallet-Auth
    depends_on: [auth-database, database, wallet-block]
    ports:
      - 8000:8000

  wallet-admin:
    build: Wallet-Admin
    depends_on: [auth-database, database]
    ports:
      - 4500:4500

  wallet-sync:
    build: Wallet-Sync
    depends_on: [database]
    ports:
      - 7000:7000

  wallet-transaction:
    build: Wallet-Transaction
    depends_on: [database, wallet-block]
    ports:
      - 10000:10000
