version: "3"

services:
  database:
    build: Database
    ports:
      - 5432:5432

  cache:
    image: redis
    ports:
      - 6379:6379

  wallet-block:
    build: Wallet-Block
    depends_on: [cache, database]
    ports:
      - 9000:9000

  wallet-profile:
    build: Wallet-Profile
    depends_on: [database, wallet-block]
    ports:
      - 8000:8000

  wallet-admin:
    build: Wallet-Admin
    depends_on: [database]
    ports:
      - 4500:4500

  mart:
    build: Mart
    depends_on: [database, wallet-block]
    ports:
      - 4600:4600

  wallet-sync:
    build: Wallet-Sync
    depends_on: [database]
    ports:
      - 7000:7000

  wallet-transaction:
    build: Wallet-Transaction
    depends_on: [database, wallet-block]
    ports:
      - 10000:10000

  nginx-proxy:
      image: nginx-proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
      restart: always
      privileged: true
