version: "3"

services:
  database:
    build: Database
    ports:
      - 5432:5432

  admin:
    build: Admin
    depends_on: [database]
    ports:
      - 4500:4500
    environment:
      VIRTUAL_HOST: admin.ec2-3-17-161-20.us-east-2.compute.amazonaws.com

  block:
    build: Block
    depends_on: [database]
    ports:
      - 9000:9000
    environment:
      VIRTUAL_HOST: block.localhost

  profile:
    build: Profile
    depends_on: [database, block]
    ports:
      - 8000:8000
    environment:
      VIRTUAL_HOST: profile.localhost

  mart:
    build: Mart
    depends_on: [database, block]
    ports:
      - 4600:4600
    environment:
      VIRTUAL_HOST: mart.localhost

  sync:
    build: Sync
    depends_on: [database]
    ports:
      - 7000:7000
    environment:
      VIRTUAL_HOST: sync.localhost

  transaction:
    build: Transaction
    depends_on: [database, block]
    ports:
      - 9500:9500
    environment:
      VIRTUAL_HOST: transaction.localhost

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    privileged: true
